ARG FROM=docker.io/fluent/fluentd-kubernetes-daemonset:v1.15-debian-elasticsearch7-1
FROM ${FROM}

RUN set -ex \
 && apt-get update \
 && apt-get install -y gcc make \
 && gem install \
      fluent-plugin-kafka \
      fluent-plugin-systemd:1.0.5 \
      fluent-plugin-prometheus \
 && apt-get purge -y --autoremove gcc make \
 && rm -rf /var/lib/apt/lists/*
