FROM docker.io/fluent/fluentd-kubernetes-daemonset:v1.10.1-debian-elasticsearch7-1.0

RUN set -ex; \
    apt-get update; \
    apt-get install -y gcc make; \
    gem install \
      fluent-plugin-kafka \
      fluent-plugin-systemd:1.0.1 \
      fluent-plugin-prometheus; \
    apt-get purge -y gcc make
