# syntax=docker/dockerfile:1
ARG FROM=fluent/fluentd-kubernetes-daemonset:v1.19-debian-elasticsearch8-1
FROM ${FROM}

RUN set -ex \
 && apt-get update \
 && apt-get install -y gcc make \
 && gem install \
      fluent-plugin-kafka \
 && apt-get purge -y --autoremove gcc make \
 && rm -rf /var/lib/apt/lists/*
