ARG FROM=docker.io/ubuntu:jammy
FROM ${FROM}

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

RUN set -ex && \
    apt-get update && \
    apt-get install -y openvswitch-switch && \
    rm -rf /var/lib/apt/lists/* && \
    useradd -u 42424 openvswitch && \
    chown -R openvswitch:openvswitch /var/lib/openvswitch /etc/openvswitch
