ARG FROM=docker.io/ubuntu:bionic
FROM ${FROM}
LABEL maintainer="cheng1.li@intel.com"

RUN set -ex; \
    apt-get update; \
    apt-get install -y openvswitch-switch; \
    rm -rf /var/lib/apt/lists/*
