FROM docker.elastic.co/elasticsearch/elasticsearch:7.6.2

RUN yum install -y epel-release; \
    yum update; \
    yum install -y python-pip jq; \
    pip install --upgrade pip; \
    pip install \
      elasticsearch==7.8.0 \
      elasticsearch-dsl==7.2.1; \
    bin/elasticsearch-plugin install --batch repository-s3; \
    rm -rf /var/cache/yum
