FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.0

RUN wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 \
        && chmod +x ./jq \
        && cp jq /usr/bin

RUN bin/elasticsearch-plugin install --batch repository-s3
