# syntax=docker/dockerfile:1
ARG FROM=quay.io/airshipit/ubuntu:noble
FROM ${FROM}

ARG TARGETARCH
ARG TARGETPLATFORM

ARG VENV=/osh-selenium_venv
ENV PATH=${VENV}/bin:$PATH

COPY script.sh /script.sh
RUN /script.sh && rm -f /script.sh
