FROM docker.io/mariadb@sha256:447c20d3ca6a4c91bad29a4792d9825abf856f984b23d66f654852cf7cd757d2
#FROM docker.io/mariadb:10.2.31

RUN set -ex ;\
    apt-get update ;\
    apt-get upgrade -y ;\
    apt-get install -y --no-install-recommends \
        python3-pip ;\
    pip3 --no-cache-dir install --upgrade pip ;\
    hash -r ;\
    pip3 --no-cache-dir install --upgrade setuptools ;\
    pip3 --no-cache-dir install --upgrade \
      configparser \
      iso8601 \
      kubernetes ;\
    apt-get clean -y ;\
    rm -rf \
       /var/cache/debconf/* \
       /var/lib/apt/lists/* \
       /var/log/* \
       /tmp/* \
       /var/tmp/* ;\
    usermod -s /bin/false mysql
