ARG FROM=ubuntu:20.04
FROM ${FROM}

RUN set -ex ;\
    export DEBIAN_FRONTEND=noninteractive ;\
    apt-get update ;\
    apt-get upgrade -y ;\
    apt-get install netbase -y ;\
    apt-get install --no-install-recommends -y \
        python3-dev \
        build-essential \
        python3-pip \
        libssl-dev \
        git ;\
    pip3 install -U pip ;\
    git clone https://git.openstack.org/openstack/tempest ;\
    git clone https://git.openstack.org/openstack/barbican-tempest-plugin ;\
    git clone https://git.openstack.org/openstack/cinder-tempest-plugin ;\
    git clone https://git.openstack.org/openstack/heat-tempest-plugin ;\
    git clone https://git.openstack.org/openstack/keystone-tempest-plugin ;\
    git clone https://git.openstack.org/openstack/neutron-tempest-plugin ;\
    git clone https://git.openstack.org/openstack/requirements ;\
    pip3 install -U setuptools==58.0.0 ;\
    pip3 install wheel ;\
    pip3 install -c requirements/upper-constraints.txt \
                    tempest/ \
                    barbican-tempest-plugin/ \
                    cinder-tempest-plugin/ \
                    heat-tempest-plugin/ \
                    keystone-tempest-plugin/ \
                    neutron-tempest-plugin/ ;\
