---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- job:
    name: openstack-helm-images-buildset-registry
    parent: opendev-buildset-registry
    timeout: 10800
    voting: false

# In docker_images:
# `context` is the folder in osh-images
# `repository` is the repo on quay.io/airshipit
# `tags` is a list of the tags when promoted
#   (images are published with change id)
# `dockerfile`. Explicit.
- job:
    name: openstack-helm-images-build
    nodeset: openstack-helm-images-ubuntu-noble
    abstract: true
    match-on-config-updates: false
    roles:
      - zuul: openstack/openstack-helm-images
      - zuul: zuul/zuul-jobs
    pre-run:
      - playbooks/inject-keys.yaml
      - playbooks/pre-build.yaml
    run: playbooks/build.yml
    dependencies:
      - name: openstack-helm-images-buildset-registry
    irrelevant-files: &irrelevant_files
      - ^\.git.*
      - ^.*\.(example|md|rst)$
      - ^doc/.*
      - ^releasenotes/.*
    timeout: 10800

# The child upload jobs must have dependencies
# on the buildset regitsty jobs and on build jobs
# for the images they are going to upload.
- job:
    name: openstack-helm-images-upload
    abstract: true
    match-on-config-updates: false
    roles:
      - zuul: openstack/openstack-helm-images
      - zuul: zuul/zuul-jobs
    timeout: 10800
    pre-run:
      - playbooks/inject-keys.yaml
      - playbooks/pre-build.yaml
    run:
      - playbooks/upload.yaml
    irrelevant-files: *irrelevant_files
    secrets:
      name: container_registry_credentials
      secret: openstack-helm-images_registry_credentials


# The child promote job must be run after upload job.
- job:
    name: openstack-helm-images-promote
    abstract: true
    match-on-config-updates: false
    roles:
      - zuul: openstack/openstack-helm-images
      - zuul: zuul/zuul-jobs
    pre-run:
      - playbooks/inject-keys.yaml
      - playbooks/pre-build.yaml
    run:
      - playbooks/promote.yaml
    secrets:
      name: container_registry_credentials
      secret: openstack-helm-images_registry_credentials

- job:
    name: openstack-helm-images-build-base
    parent: openstack-helm-images-build
    vars: &base_vars
      set_base_registry_prefix: true
      currentdate: "{{ now(utc=True,fmt='%Y%m%d') }}"
      container_images:
        - context: .
          registry: quay.io
          repository: quay.io/airshipit/base
          container_filename: base/Dockerfile
          arch:
            - linux/amd64
            - linux/arm64
          tags:
            - "2025.1-ubuntu_noble"
            - "2025.1-ubuntu_noble-{{ currentdate }}"
          build_args:
            - "FROM='public.ecr.aws/ubuntu/ubuntu:noble'"
        - context: .
          registry: quay.io
          repository: quay.io/airshipit/base
          container_filename: base/Dockerfile
          arch:
            - linux/amd64
            - linux/arm64
          tags:
            - "2025.2-ubuntu_noble"
            - "2025.2-ubuntu_noble-{{ currentdate }}"
          build_args:
            - "FROM='public.ecr.aws/ubuntu/ubuntu:noble'"
        - context: .
          registry: quay.io
          repository: quay.io/airshipit/base
          container_filename: base/Dockerfile
          arch:
            - linux/amd64
            - linux/arm64
          tags:
            - "2026.1-ubuntu_noble"
            - "2026.1-ubuntu_noble-{{ currentdate }}"
          build_args:
            - "FROM='public.ecr.aws/ubuntu/ubuntu:noble'"

- job:
    name: openstack-helm-images-upload-base
    parent: openstack-helm-images-upload
    description: Build and upload base images
    dependencies:
      - name: openstack-helm-images-buildset-registry
      - name: openstack-helm-images-build-base
    vars: *base_vars

- job:
    name: openstack-helm-images-promote-base
    parent: openstack-helm-images-promote
    description: Promote a previously published base image to latest.
    vars: *base_vars
