---
# Copyright 2019, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    vars:
      helm_version: "3.18.1"

    check:
      jobs:
        - openstack-helm-images-buildset-registry
        - openstack-helm-images-monitoring
        - openstack-helm-images-logging
    gate:
      jobs:
        - openstack-helm-images-buildset-registry
        - openstack-helm-images-monitoring
        - openstack-helm-images-logging
    periodic-weekly:
      jobs:
        - openstack-helm-images-buildset-registry
        - openstack-helm-images-monitoring
        - openstack-helm-images-logging
    periodic:
      jobs:
        - openstack-helm-images-buildset-registry
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

- job:
    name: openstack-helm-images-buildset-registry
    parent: opendev-buildset-registry
    timeout: 10800
    voting: false

# In docker_images:
# `context` is the folder in osh-images
# `repository` is the repo on quay.io/airshipit
# `tags` is a list of the tags when promoted
#   (images are published with change id)
# `dockerfile`. Explicit.
- job:
    name: openstack-helm-images-build
    abstract: true
    match-on-config-updates: false
    roles:
      - zuul: openstack/openstack-helm-images
      - zuul: zuul/zuul-jobs
    pre-run:
      - playbooks/inject-keys.yaml
      - playbooks/pre-build.yaml
    run: playbooks/build.yml
    dependencies:
      - name: openstack-helm-images-buildset-registry
    irrelevant-files: &irrelevant_files
      - ^\.git.*
      - ^.*\.(example|md|rst)$
      - ^doc/.*
      - ^releasenotes/.*
    timeout: 3600

# The child upload jobs must have dependencies
# on the buildset regitsty jobs and on build jobs
# for the images they are going to upload.
- job:
    name: openstack-helm-images-upload
    abstract: true
    match-on-config-updates: false
    roles:
      - zuul: openstack/openstack-helm-images
      - zuul: zuul/zuul-jobs
    timeout: 10800
    pre-run:
      - playbooks/inject-keys.yaml
      - playbooks/pre-build.yaml
    run:
      - playbooks/upload.yaml
    irrelevant-files: *irrelevant_files
    secrets:
      name: container_registry_credentials
      secret: openstack-helm-images_registry_credentials


# The child promote job must be run after upload job.
- job:
    name: openstack-helm-images-promote
    abstract: true
    match-on-config-updates: false
    roles:
      - zuul: openstack/openstack-helm-images
      - zuul: zuul/zuul-jobs
    pre-run:
      - playbooks/inject-keys.yaml
      - playbooks/pre-build.yaml
    run:
      - playbooks/promote.yaml
    secrets:
      name: container_registry_credentials
      secret: openstack-helm-images_registry_credentials

# Image testing jobs inheriting from osh jobs running against
# particular image or set of images.
- job:
    name: openstack-helm-images-monitoring
    parent: openstack-helm-monitoring
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-osh-selenium
        soft: true
      - name: openstack-helm-images-build-node-problem-detector
        soft: true
      - name: openstack-helm-images-build-nagios
        soft: true
    files:
      - osh-selenium/.*
      - zuul.d/osh-selenium.yaml
      - node-problem-detector/.*
      - zuul.d/node-problem-detector.yaml
      - nagios/.*
      - zuul.d/nagios.yaml

- job:
    name: openstack-helm-images-logging
    parent: openstack-helm-logging
    match-on-config-updates: false
    dependencies:
      - name: openstack-helm-images-build-fluentd
        soft: true
      - name: openstack-helm-images-build-osh-selenium
        soft: true
    files:
      - fluentd/.*
      - zuul.d/fluentd.yaml
      - zuul.d/elasticsearch-s3.yaml
      - osh-selenium/.*
      - zuul.d/osh-selenium.yaml
