ARG FROM=docker.io/ubuntu:bionic
FROM ${FROM}

ARG UID=42424

RUN set -ex && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y \
      openssh-server \
      openssh-client && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -r -u ${UID} -d /var/lib/nova nova && \
    chown -R nova: /etc/ssh && \
    mkdir /var/run/sshd && \
    chmod 0755 /var/run/sshd
