ARG FROM=ubuntu:jammy
FROM ${FROM}

ARG OPENSTACK_RELEASE=2023.2
ARG UPPER_CONSTRAINTS_FILE=https://releases.openstack.org/constraints/upper/${OPENSTACK_RELEASE}

RUN apt-get update && apt-get install -y \
      python3-pip \
      && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip && \
  pip3 install \
  -c${UPPER_CONSTRAINTS_FILE} \
  cmd2 \
  python-barbicanclient \
  python-blazarclient \
  python-cinderclient \
  python-designateclient \
  python-glanceclient \
  python-heatclient \
  python-ironicclient \
  python-keystoneclient \
  python-magnumclient \
  python-manilaclient \
  python-mistralclient \
  python-monascaclient \
  python-neutronclient \
  python-novaclient \
  python-octaviaclient \
  python-openstackclient \
  python-saharaclient \
  python-swiftclient \
  python-tackerclient \
  python-troveclient \
  python-vitrageclient \
  python-watcherclient \
  python-zaqarclient \
  python-zunclient \
  --ignore-installed

